import type { ConnectorProvider } from './connectors';

/**
 * Edi's short list of apps. Remote MCP servers sign in with their own OAuth; the rest go through
 * the person's Composio project, which holds each app's OAuth client. Only apps with
 * Composio-managed sign-in are listed (X has none). Each Composio app names the tools Edi
 * switches on by default: everyday reading, writing and organizing, checked against Composio's
 * toolkit docs (docs.composio.dev/toolkits/<slug>.md). The rest are listed but start off.
 */
export type ConnectorCategory =
  | 'communication'
  | 'productivity'
  | 'files'
  | 'development'
  | 'design'
  | 'data'
  | 'marketing'
  | 'other';

export interface CatalogEntry {
  id: string;
  name: string;
  description: string;
  category: ConnectorCategory;
  provider: ConnectorProvider;
  /** MCP server URL (provider: mcp) or Composio toolkit slug (provider: composio). */
  url: string;
  /** Tools on by default; any others the app offers are listed but start off. */
  tools?: readonly string[];
}

/** Direct MCP servers with their own OAuth and PKCE. */
const mcpApps: CatalogEntry[] = [
  {
    id: 'notion',
    name: 'Notion',
    url: 'https://mcp.notion.com/mcp',
    description: 'Search, read and update pages and databases in your workspace.',
    category: 'productivity',
    provider: 'mcp',
  },
  {
    id: 'linear',
    name: 'Linear',
    url: 'https://mcp.linear.app/mcp',
    description: 'Find, create and update issues, projects and comments.',
    category: 'development',
    provider: 'mcp',
  },
  {
    id: 'asana',
    name: 'Asana',
    url: 'https://mcp.asana.com/mcp',
    description: 'Look up and manage tasks, projects and teammates’ work.',
    category: 'productivity',
    provider: 'mcp',
  },
];

/** Apps connected through Composio. */
const composioApps: CatalogEntry[] = [
  {
    id: 'gmail',
    name: 'Gmail',
    url: 'gmail',
    description: 'Search, read, draft and send email, and keep your inbox labelled.',
    category: 'communication',
    provider: 'composio',
    tools: [
      'GMAIL_FETCH_EMAILS',
      'GMAIL_FETCH_MESSAGE_BY_MESSAGE_ID',
      'GMAIL_FETCH_MESSAGE_BY_THREAD_ID',
      'GMAIL_LIST_THREADS',
      'GMAIL_SEND_EMAIL',
      'GMAIL_REPLY_TO_THREAD',
      'GMAIL_CREATE_EMAIL_DRAFT',
      'GMAIL_FORWARD_MESSAGE',
      'GMAIL_LIST_LABELS',
      'GMAIL_ADD_LABEL_TO_EMAIL',
      'GMAIL_MOVE_TO_TRASH',
      'GMAIL_SEARCH_PEOPLE',
      'GMAIL_GET_ATTACHMENT',
    ],
  },
  {
    id: 'outlook',
    name: 'Outlook',
    url: 'outlook',
    description: 'Read and send Outlook email and check your Outlook calendar.',
    category: 'communication',
    provider: 'composio',
    tools: [
      'OUTLOOK_SEARCH_MESSAGES',
      'OUTLOOK_LIST_MESSAGES',
      'OUTLOOK_GET_MESSAGE',
      'OUTLOOK_SEND_EMAIL',
      'OUTLOOK_REPLY_EMAIL',
      'OUTLOOK_CREATE_DRAFT',
      'OUTLOOK_LIST_EVENTS',
      'OUTLOOK_CALENDAR_CREATE_EVENT',
      'OUTLOOK_GET_SCHEDULE',
      'OUTLOOK_LIST_CONTACTS',
    ],
  },
  {
    id: 'slack',
    name: 'Slack',
    url: 'slack',
    description: 'Search conversations, catch up on threads and send messages.',
    category: 'communication',
    provider: 'composio',
    tools: [
      'SLACK_SEARCH_MESSAGES',
      'SLACK_FETCH_CONVERSATION_HISTORY',
      'SLACK_FETCH_MESSAGE_THREAD_FROM_A_CONVERSATION',
      'SLACK_LIST_CONVERSATIONS',
      'SLACK_FIND_CHANNELS',
      'SLACK_FIND_USERS',
      'SLACK_SEND_MESSAGE',
      'SLACK_SCHEDULE_MESSAGE',
      'SLACK_ADD_REACTION_TO_AN_ITEM',
      'SLACK_CREATE_A_REMINDER',
      'SLACK_LIST_UNREAD_CHANNEL_MESSAGES',
    ],
  },
  {
    id: 'microsoft_teams',
    name: 'Microsoft Teams',
    url: 'microsoft_teams',
    description: 'Read chats and channels, post messages and set up meetings.',
    category: 'communication',
    provider: 'composio',
    tools: [
      'MICROSOFT_TEAMS_CHATS_GET_ALL_CHATS',
      'MICROSOFT_TEAMS_CHATS_GET_ALL_MESSAGES',
      'MICROSOFT_TEAMS_TEAMS_LIST',
      'MICROSOFT_TEAMS_TEAMS_LIST_CHANNELS',
      'MICROSOFT_TEAMS_TEAMS_POST_CHANNEL_MESSAGE',
      'MICROSOFT_TEAMS_SEARCH_MESSAGES',
      'MICROSOFT_TEAMS_CREATE_MEETING',
      'MICROSOFT_TEAMS_GET_MEETING_TRANSCRIPT_CONTENT',
      'MICROSOFT_TEAMS_TEAMS_POST_CHAT_MESSAGE',
      'MICROSOFT_TEAMS_TEAMS_LIST_CHANNEL_MESSAGES',
    ],
  },
  {
    id: 'zoom',
    name: 'Zoom',
    url: 'zoom',
    description: 'See and schedule meetings, and read summaries and recordings.',
    category: 'communication',
    provider: 'composio',
    tools: [
      'ZOOM_LIST_MEETINGS',
      'ZOOM_GET_A_MEETING',
      'ZOOM_CREATE_A_MEETING',
      'ZOOM_UPDATE_A_MEETING',
      'ZOOM_GET_A_MEETING_SUMMARY',
      'ZOOM_GET_MEETING_RECORDINGS',
      'ZOOM_LIST_ALL_RECORDINGS',
      'ZOOM_GET_PAST_MEETING_PARTICIPANTS',
    ],
  },
  {
    id: 'googlemeet',
    name: 'Google Meet',
    url: 'googlemeet',
    description: 'Start meetings and read transcripts of past ones.',
    category: 'communication',
    provider: 'composio',
    tools: [
      'GOOGLEMEET_CREATE_MEET',
      'GOOGLEMEET_GET_MEET',
      'GOOGLEMEET_LIST_CONFERENCE_RECORDS',
      'GOOGLEMEET_GET_TRANSCRIPTS_BY_CONFERENCE_RECORD_ID',
      'GOOGLEMEET_LIST_TRANSCRIPT_ENTRIES',
      'GOOGLEMEET_GET_RECORDINGS_BY_CONFERENCE_RECORD_ID',
      'GOOGLEMEET_LIST_PARTICIPANTS',
    ],
  },
  {
    id: 'googlecalendar',
    name: 'Google Calendar',
    url: 'googlecalendar',
    description: 'See your schedule, find free time and add or move events.',
    category: 'productivity',
    provider: 'composio',
    tools: [
      'GOOGLECALENDAR_EVENTS_LIST',
      'GOOGLECALENDAR_EVENTS_LIST_ALL_CALENDARS',
      'GOOGLECALENDAR_FIND_EVENT',
      'GOOGLECALENDAR_FIND_FREE_SLOTS',
      'GOOGLECALENDAR_EVENTS_GET',
      'GOOGLECALENDAR_LIST_CALENDARS',
      'GOOGLECALENDAR_CREATE_EVENT',
      'GOOGLECALENDAR_QUICK_ADD',
      'GOOGLECALENDAR_PATCH_EVENT',
      'GOOGLECALENDAR_DELETE_EVENT',
    ],
  },
  {
    id: 'calendly',
    name: 'Calendly',
    url: 'calendly',
    description: 'See booked meetings and share one-off scheduling links.',
    category: 'productivity',
    provider: 'composio',
    tools: [
      'CALENDLY_GET_CURRENT_USER',
      'CALENDLY_LIST_EVENT_TYPES',
      'CALENDLY_LIST_EVENTS',
      'CALENDLY_GET_EVENT',
      'CALENDLY_LIST_EVENT_INVITEES',
      'CALENDLY_LIST_EVENT_TYPE_AVAILABLE_TIMES',
      'CALENDLY_CREATE_SINGLE_USE_SCHEDULING_LINK',
      'CALENDLY_CANCEL_SCHEDULED_EVENT',
    ],
  },
  {
    id: 'googledocs',
    name: 'Google Docs',
    url: 'googledocs',
    description: 'Find, read, write and update documents.',
    category: 'productivity',
    provider: 'composio',
    tools: [
      'GOOGLEDOCS_SEARCH_DOCUMENTS',
      'GOOGLEDOCS_GET_DOCUMENT_PLAINTEXT',
      'GOOGLEDOCS_GET_DOCUMENT_BY_ID',
      'GOOGLEDOCS_CREATE_DOCUMENT_MARKDOWN',
      'GOOGLEDOCS_UPDATE_DOCUMENT_MARKDOWN',
      'GOOGLEDOCS_INSERT_TEXT_ACTION',
      'GOOGLEDOCS_COPY_DOCUMENT',
      'GOOGLEDOCS_EXPORT_DOCUMENT_AS_PDF',
    ],
  },
  {
    id: 'googletasks',
    name: 'Google Tasks',
    url: 'googletasks',
    description: 'Keep your to-do lists: add, update and finish tasks.',
    category: 'productivity',
    provider: 'composio',
    tools: [
      'GOOGLETASKS_LIST_TASK_LISTS',
      'GOOGLETASKS_LIST_TASKS',
      'GOOGLETASKS_LIST_ALL_TASKS',
      'GOOGLETASKS_GET_TASK',
      'GOOGLETASKS_INSERT_TASK',
      'GOOGLETASKS_PATCH_TASK',
      'GOOGLETASKS_DELETE_TASK',
      'GOOGLETASKS_CREATE_TASK_LIST',
    ],
  },
  {
    id: 'todoist',
    name: 'Todoist',
    url: 'todoist',
    description: 'Add, plan and complete tasks and projects.',
    category: 'productivity',
    provider: 'composio',
    tools: [
      'TODOIST_GET_ALL_TASKS',
      'TODOIST_FILTER_TASKS',
      'TODOIST_GET_TASK',
      'TODOIST_QUICK_ADD_TASK',
      'TODOIST_CREATE_TASK',
      'TODOIST_UPDATE_TASK',
      'TODOIST_CLOSE_TASK',
      'TODOIST_GET_ALL_PROJECTS',
      'TODOIST_CREATE_PROJECT',
      'TODOIST_LIST_COMPLETED_TASKS',
    ],
  },
  {
    id: 'trello',
    name: 'Trello',
    url: 'trello',
    description: 'Look through boards and cards, add cards and leave comments.',
    category: 'productivity',
    provider: 'composio',
    tools: [
      'TRELLO_GET_MEMBERS_BOARDS_BY_ID_MEMBER',
      'TRELLO_GET_BOARDS_LISTS_BY_ID_BOARD',
      'TRELLO_GET_BOARDS_CARDS_BY_ID_BOARD',
      'TRELLO_GET_CARDS_BY_ID_CARD',
      'TRELLO_ADD_CARDS',
      'TRELLO_UPDATE_CARDS_BY_ID_CARD',
      'TRELLO_ADD_CARDS_ACTIONS_COMMENTS_BY_ID_CARD',
      'TRELLO_ADD_CHECKLIST_ITEM',
      'TRELLO_GET_SEARCH',
    ],
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    url: 'clickup',
    description: 'Find, create and update tasks, and read ClickUp docs.',
    category: 'productivity',
    provider: 'composio',
    tools: [
      'CLICKUP_GET_FILTERED_TEAM_TASKS',
      'CLICKUP_GET_TASK',
      'CLICKUP_GET_TASKS',
      'CLICKUP_CREATE_TASK',
      'CLICKUP_UPDATE_TASK',
      'CLICKUP_CREATE_TASK_COMMENT',
      'CLICKUP_GET_SPACES',
      'CLICKUP_GET_LISTS',
      'CLICKUP_SEARCH_DOCS',
      'CLICKUP_GET_DOC_CONTENT',
    ],
  },
  {
    id: 'googledrive',
    name: 'Google Drive',
    url: 'googledrive',
    description: 'Find, read, organize and share files in Drive.',
    category: 'files',
    provider: 'composio',
    tools: [
      'GOOGLEDRIVE_FIND_FILE',
      'GOOGLEDRIVE_FIND_FOLDER',
      'GOOGLEDRIVE_LIST_FILES',
      'GOOGLEDRIVE_GET_FILE_METADATA',
      'GOOGLEDRIVE_DOWNLOAD_FILE',
      'GOOGLEDRIVE_EXPORT_GOOGLE_WORKSPACE_FILE',
      'GOOGLEDRIVE_CREATE_FILE_FROM_TEXT',
      'GOOGLEDRIVE_CREATE_FOLDER',
      'GOOGLEDRIVE_MOVE_FILE',
      'GOOGLEDRIVE_COPY_FILE',
      'GOOGLEDRIVE_ADD_FILE_SHARING_PREFERENCE',
    ],
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    url: 'dropbox',
    description: 'Search, read, upload and share Dropbox files.',
    category: 'files',
    provider: 'composio',
    tools: [
      'DROPBOX_FILES_SEARCH',
      'DROPBOX_LIST_FILES_IN_FOLDER',
      'DROPBOX_GET_METADATA',
      'DROPBOX_READ_FILE',
      'DROPBOX_UPLOAD_FILE',
      'DROPBOX_CREATE_FOLDER',
      'DROPBOX_MOVE_FILE_OR_FOLDER',
      'DROPBOX_CREATE_SHARED_LINK_SIMPLE',
    ],
  },
  {
    id: 'one_drive',
    name: 'OneDrive',
    url: 'one_drive',
    description: 'Find, read, upload and share files in OneDrive.',
    category: 'files',
    provider: 'composio',
    tools: [
      'ONE_DRIVE_SEARCH_ITEMS',
      'ONE_DRIVE_ONEDRIVE_FIND_FILE',
      'ONE_DRIVE_ONEDRIVE_LIST_ITEMS',
      'ONE_DRIVE_GET_RECENT_ITEMS',
      'ONE_DRIVE_GET_ITEM',
      'ONE_DRIVE_DOWNLOAD_FILE',
      'ONE_DRIVE_ONEDRIVE_UPLOAD_FILE',
      'ONE_DRIVE_ONEDRIVE_CREATE_FOLDER',
      'ONE_DRIVE_MOVE_ITEM',
      'ONE_DRIVE_CREATE_LINK',
    ],
  },
  {
    id: 'github',
    name: 'GitHub',
    url: 'github',
    description: 'Search code, repos, issues and pull requests, and file issues.',
    category: 'development',
    provider: 'composio',
    tools: [
      'GITHUB_SEARCH_REPOSITORIES',
      'GITHUB_SEARCH_ISSUES_AND_PULL_REQUESTS',
      'GITHUB_SEARCH_CODE',
      'GITHUB_GET_A_REPOSITORY',
      'GITHUB_GET_REPOSITORY_CONTENT',
      'GITHUB_LIST_REPOSITORY_ISSUES',
      'GITHUB_GET_AN_ISSUE',
      'GITHUB_CREATE_AN_ISSUE',
      'GITHUB_CREATE_AN_ISSUE_COMMENT',
      'GITHUB_LIST_PULL_REQUESTS',
      'GITHUB_GET_A_PULL_REQUEST',
      'GITHUB_LIST_NOTIFICATIONS_FOR_THE_AUTHENTICATED_USER',
      'GITHUB_GET_THE_AUTHENTICATED_USER',
    ],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    url: 'gitlab',
    description: 'Browse projects, issues and merge requests, and comment on them.',
    category: 'development',
    provider: 'composio',
    tools: [
      'GITLAB_GET_PROJECTS',
      'GITLAB_GET_PROJECT',
      'GITLAB_LIST_PROJECT_ISSUES',
      'GITLAB_GET_ISSUE',
      'GITLAB_CREATE_PROJECT_ISSUE',
      'GITLAB_CREATE_ISSUE_NOTE',
      'GITLAB_LIST_MERGE_REQUESTS',
      'GITLAB_GET_PROJECT_MERGE_REQUEST',
      'GITLAB_GET_MERGE_REQUEST_NOTES',
      'GITLAB_GET_RAW_FILE',
      'GITLAB_GET_CURRENT_USER',
    ],
  },
  {
    id: 'jira',
    name: 'Jira',
    url: 'jira',
    description: 'Search, create, update and move issues through their workflow.',
    category: 'development',
    provider: 'composio',
    tools: [
      'JIRA_SEARCH_ISSUES',
      'JIRA_GET_ISSUE',
      'JIRA_CREATE_ISSUE',
      'JIRA_EDIT_ISSUE',
      'JIRA_ADD_COMMENT',
      'JIRA_LIST_ISSUE_COMMENTS',
      'JIRA_GET_TRANSITIONS',
      'JIRA_TRANSITION_ISSUE',
      'JIRA_ASSIGN_ISSUE',
      'JIRA_GET_ALL_PROJECTS',
      'JIRA_GET_CURRENT_USER',
    ],
  },
  {
    id: 'figma',
    name: 'Figma',
    url: 'figma',
    description: 'Read files, components, styles and comments; export frames as images.',
    category: 'design',
    provider: 'composio',
    tools: [
      'FIGMA_GET_FILE_JSON',
      'FIGMA_GET_FILE_NODES',
      'FIGMA_RENDER_IMAGES_OF_FILE_NODES',
      'FIGMA_GET_COMMENTS_IN_A_FILE',
      'FIGMA_ADD_A_COMMENT_TO_A_FILE',
      'FIGMA_GET_FILE_COMPONENTS',
      'FIGMA_GET_FILE_STYLES',
      'FIGMA_GET_LOCAL_VARIABLES',
      'FIGMA_GET_FILES_IN_A_PROJECT',
      'FIGMA_GET_PROJECTS_IN_A_TEAM',
    ],
  },
  {
    id: 'miro',
    name: 'Miro',
    url: 'miro',
    description: 'Read boards and add sticky notes, text, shapes and connectors.',
    category: 'design',
    provider: 'composio',
    tools: [
      'MIRO_GET_BOARDS',
      'MIRO_GET_SPECIFIC_BOARD',
      'MIRO_GET_BOARD_ITEMS',
      'MIRO_CREATE_BOARD',
      'MIRO_CREATE_STICKY_NOTE_ITEM',
      'MIRO_CREATE_TEXT_ITEM',
      'MIRO_CREATE_SHAPE_ITEM',
      'MIRO_CREATE_CONNECTOR',
      'MIRO_CREATE_ITEMS_IN_BULK',
    ],
  },
  {
    id: 'googlesheets',
    name: 'Google Sheets',
    url: 'googlesheets',
    description: 'Find spreadsheets, read ranges and add or update rows.',
    category: 'data',
    provider: 'composio',
    tools: [
      'GOOGLESHEETS_SEARCH_SPREADSHEETS',
      'GOOGLESHEETS_GET_SPREADSHEET_INFO',
      'GOOGLESHEETS_GET_SHEET_NAMES',
      'GOOGLESHEETS_BATCH_GET',
      'GOOGLESHEETS_VALUES_GET',
      'GOOGLESHEETS_LOOKUP_SPREADSHEET_ROW',
      'GOOGLESHEETS_CREATE_GOOGLE_SHEET1',
      'GOOGLESHEETS_SPREADSHEETS_VALUES_APPEND',
      'GOOGLESHEETS_VALUES_UPDATE',
      'GOOGLESHEETS_ADD_SHEET',
    ],
  },
  {
    id: 'excel',
    name: 'Excel',
    url: 'excel',
    description: 'Read worksheets and tables, and update ranges and rows.',
    category: 'data',
    provider: 'composio',
    tools: [
      'EXCEL_SEARCH_FILES',
      'EXCEL_LIST_WORKSHEETS',
      'EXCEL_GET_WORKSHEET_USED_RANGE',
      'EXCEL_GET_RANGE',
      'EXCEL_LIST_TABLES',
      'EXCEL_LIST_TABLE_ROWS',
      'EXCEL_UPDATE_RANGE',
      'EXCEL_ADD_TABLE_ROW',
      'EXCEL_CREATE_WORKBOOK',
      'EXCEL_ADD_WORKSHEET',
    ],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    url: 'airtable',
    description: 'Read bases and records, and add or update records.',
    category: 'data',
    provider: 'composio',
    tools: [
      'AIRTABLE_LIST_BASES',
      'AIRTABLE_GET_BASE_SCHEMA',
      'AIRTABLE_LIST_RECORDS',
      'AIRTABLE_GET_RECORD',
      'AIRTABLE_CREATE_RECORD',
      'AIRTABLE_UPDATE_RECORD',
      'AIRTABLE_CREATE_COMMENT',
    ],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    url: 'linkedin',
    description: 'Share posts and articles, and look up companies.',
    category: 'marketing',
    provider: 'composio',
    tools: [
      'LINKEDIN_GET_MY_INFO',
      'LINKEDIN_CREATE_LINKED_IN_POST',
      'LINKEDIN_CREATE_ARTICLE_OR_URL_SHARE',
      'LINKEDIN_CREATE_COMMENT_ON_POST',
      'LINKEDIN_GET_COMPANY_INFO',
      'LINKEDIN_GET_POST_CONTENT',
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    url: 'youtube',
    description: 'Search videos, read captions and manage your playlists.',
    category: 'marketing',
    provider: 'composio',
    tools: [
      'YOUTUBE_SEARCH_YOU_TUBE',
      'YOUTUBE_LIST_CAPTION_TRACK',
      'YOUTUBE_LIST_USER_PLAYLISTS',
      'YOUTUBE_LIST_PLAYLIST_ITEMS',
      'YOUTUBE_ADD_VIDEO_TO_PLAYLIST',
      'YOUTUBE_GET_CHANNEL_STATISTICS',
      'YOUTUBE_LIST_CHANNEL_VIDEOS',
    ],
  },
  {
    id: 'reddit',
    name: 'Reddit',
    url: 'reddit',
    description: 'Search subreddits, read posts and comments, and post.',
    category: 'marketing',
    provider: 'composio',
    tools: [
      'REDDIT_SEARCH_ACROSS_SUBREDDITS',
      'REDDIT_GET_R_TOP',
      'REDDIT_GET_NEW',
      'REDDIT_RETRIEVE_REDDIT_POST',
      'REDDIT_RETRIEVE_POST_COMMENTS',
      'REDDIT_GET_SUBREDDITS_SEARCH',
      'REDDIT_CREATE_REDDIT_POST',
      'REDDIT_POST_REDDIT_COMMENT',
    ],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    url: 'hubspot',
    description: 'Look up and add contacts, deals, notes and tasks.',
    category: 'marketing',
    provider: 'composio',
    tools: [
      'HUBSPOT_SEARCH_CONTACTS_BY_CRITERIA',
      'HUBSPOT_READ_CONTACT',
      'HUBSPOT_CREATE_CONTACT',
      'HUBSPOT_SEARCH_COMPANIES',
      'HUBSPOT_LIST_DEALS',
      'HUBSPOT_CREATE_NOTE',
      'HUBSPOT_CREATE_TASK',
    ],
  },
];

export const connectorCatalog: readonly CatalogEntry[] = [...mcpApps, ...composioApps];
